use AUCTIONS;

DROP TABLE IF EXISTS BIDDING;
DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    /* IDENTIFIERS */
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(32) NOT NULL,

    /* BASIC INFORMATIONS */
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(13),
    EMAIL VARCHAR(30) NOT NULL, 
    CANCELED INT DEFAULT 0,/* BUYER INFORMATIONS */

    /* BUYER INFORMATIONS */
    ADDRESS VARCHAR(76), /* Addresse */
    CITY VARCHAR(25), /* Ville */
    ZIP INT, /* Code postal */
    CARD VARCHAR(16) /* Numero de Carte Bancaire */
);

CREATE TABLE ARTICLES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OWNER INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MINPRICE FLOAT NOT NULL, /* Prix de vente pre-encheres */
    CATEGORIES VARCHAR(100) NOT NULL,
    TIME DATE NOT NULL, /* Date fin de vente */
    CONSTRAINT fk_ownership
    FOREIGN KEY (OWNER) 
        REFERENCES USERS(ID)
);

CREATE TABLE BIDDING (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BIDDER INT NOT NULL,
    ITEM INT NOT NULL,
    BID FLOAT NOT NULL,
    CONSTRAINT fk_bidder
    FOREIGN KEY (BIDDER) 
        REFERENCES USERS(ID),
    CONSTRAINT fk_article
    FOREIGN KEY (ITEM) 
        REFERENCES ARTICLES(ID)
);

INSERT INTO USERS (LOGIN, PASSWORD, FIRSTNAME, LASTNAME, PHONE, EMAIL, ADDRESS, CITY, ZIP, CARD) VALUES 
('admin', 'admin', 'Administrator', 'Ofthewebsite', '+33133831132', 'admin@projet.gla', '113 Av. Administration', 'Nancy', 54000, '1234567890123456');